# Generated by Django 6.1.1 on 2026-09-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('celular', 'Celulares'), ('notebook', 'Notebooks'), ('fone', 'Fones'), ('smartwatch', 'SmartWatches')], default='celular', max_length=20),
        ),
    ]
