# Generated by Django 6.1.1 on 2026-09-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='desconto_percentual',
            field=models.PositiveIntegerField(default=15, help_text='Percentual de desconto aplicado ao preço quando "Em oferta" estiver marcado.', verbose_name='Desconto (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='em_oferta',
            field=models.BooleanField(default=False, help_text='Marque para o produto aparecer no carrossel "Ofertas do Dia" da home.', verbose_name='Em oferta'),
        ),
    ]
