# Generated by Django 6.1.1 on 2026-09-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_desconto_percentual_produto_em_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('separacao', 'Em separação'), ('enviado', 'Enviado'), ('entregue', 'Entregue')], default='recebido', max_length=20),
        ),
    ]
